# Generated by Django 5.2.11 on 2026-02-11 05:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_order_id', models.CharField(max_length=200, unique=True)),
                ('pidx', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Failed', 'Failed')], default='Initiated', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
